export const SUPABASE_URL = "https://nvswwwlaxgkzvslgoxwr.supabase.co"
export const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52c3d3d2xheGdrenZzbGdveHdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MTUwMzAsImV4cCI6MjA3MTM5MTAzMH0.vUglFeGa1vObpUbdxiSnSsyWKMdNk3K5j8RLLCUWXx8"
